"""The channel simulator's settings, one row per environment variable.

skywave-channel accepts each as a command-line flag named by one rule: drop a
leading SIM_, lowercase, underscores to hyphens (SIM_WATTERSON -> --watterson,
SIGMA -> --sigma). A test keeps this table equal to the variables
channel_sim.py actually reads.
"""

# Groups, in --help order.
GROUPS = (
    "Profiles",
    "Signal level and noise",
    "Fading",
    "Frequency and clock errors",
    "Transmitter and rig",
    "Receiver",
    "Keying and half-duplex",
    "Interference (QRM)",
    "FM channel",
    "Transport and clock",
    "Stats and debugging",
)

# (env var, group, kind, metavar, help)
#   kind "flag": channel_sim treats it as on iff the value is "1"
#   kind "value": anything else
KNOBS = (
    # --- Profiles ---
    ("SIM_PROFILE", "Profiles", "value", "NAME|FILE",
     "channel physics profile: a shipped name (clean, poor, poor-weak-ack) or a TOML/JSON file"),
    ("SIM_TRANSPORT_PROFILE", "Profiles", "value", "NAME|FILE",
     "transport profile: a shipped name (alsa-native, sock-real_time, sock-virt_time) or a TOML/JSON"),

    # --- Signal level and noise ---
    ("SIGMA", "Signal level and noise", "value", "LSB",
     "fixed channel noise std in int16 LSBs at the reference rate, added after the peak clip [0.0]"),
    ("TXGAIN", "Signal level and noise", "value", "GAIN",
     "transmitter drive level, applied before the PEP clip [1.0]"),
    ("SIM_ATTEN_DB", "Signal level and noise", "value", "DB",
     "path-loss attenuation on the signal only, after fade and before the delay line and noise [0.0]"),
    ("SIM_ATTEN_SCHEDULE", "Signal level and noise", "value", "SPEC",
     "stepped path loss over time: db:seconds,db:seconds,...; last 0 = hold; excludes SIM_ATTEN_DB"),
    ("SIM_SIGMA_AB", "Signal level and noise", "value", "LSB",
     "per-direction noise std A->B, overriding SIGMA for that direction only [SIGMA]"),
    ("SIM_SIGMA_BA", "Signal level and noise", "value", "LSB",
     "per-direction noise std B->A, overriding SIGMA for that direction only [SIGMA]"),
    ("SIM_SIGMA_BA_ONSET_S", "Signal level and noise", "value", "S",
     "delay SIM_SIGMA_BA's onset this many audio-clock seconds, running symmetric SIGMA until then"),
    ("SIM_SIGMA_REF_FS", "Signal level and noise", "value", "HZ",
     "reference rate SIGMA is specified at; 0 = SIGMA is the raw per-sample std at cable rate [48000]"),
    ("SIM_TXGAIN_A", "Signal level and noise", "value", "GAIN",
     "station A's transmit audio drive, overriding TXGAIN for A->B only [TXGAIN]"),
    ("SIM_TXGAIN_B", "Signal level and noise", "value", "GAIN",
     "station B's transmit audio drive, overriding TXGAIN for B->A only [TXGAIN]"),
    ("SIM_NOISE_ENV", "Signal level and noise", "value", "NAME",
     "P.372 man-made noise category (city, residential, rural, quiet) scaling SIGMA by band [off]"),
    ("SIM_BAND_MHZ", "Signal level and noise", "value", "MHZ",
     "band used by SIM_NOISE_ENV's P.372 scaling [7]"),
    ("SIM_NOISE_VD", "Signal level and noise", "value", "DB",
     "P.372 impulsive noise: target voltage deviation Vd, same power as SIGMA; 0 = Gaussian [0]"),
    ("SIM_NOISE_VD_K_DB", "Signal level and noise", "value", "DB",
     "impulse-to-core power ratio for SIM_NOISE_VD; caps the reachable Vd [26]"),
    ("SIM_RX_PAD_DB", "Signal level and noise", "value", "DB",
     "fixed gain on signal+noise together before the int16 cast, for ADC headroom [-12]"),
    ("SIM_RAIL_WARN_FRAC", "Signal level and noise", "value", "FRAC",
     "int16 clipping fraction that triggers the self-announcing clip warning [0.001]"),

    # --- Fading ---
    ("SIM_WATTERSON", "Fading", "value", "NAME",
     "named F.1487 multipath fade (good, moderate, poor, nvis, disturbed, high-lat, ...) or off [off]"),
    ("SIM_FADE_DOPPLER_HZ", "Fading", "value", "HZ",
     "override the named preset's Doppler spread"),
    ("SIM_FADE_DELAY_MS", "Fading", "value", "MS",
     "override the named preset's differential path delay"),
    ("SIM_FADE_DUR_S", "Fading", "value", "S",
     "length of the pre-generated fade gain sequence, cycled if the run is longer [3600]"),
    ("SIM_FADE_SEED", "Fading", "value", "N",
     "RNG seed for the fade realization [defaults to SEED]"),
    ("SIM_FADE_SCHEDULE", "Fading", "value", "SPEC",
     "time sequence of fade presets: name:seconds,name:seconds,...; last 0 = rest of run"),
    ("SIM_FADE_XFADE_S", "Fading", "value", "S",
     "crossfade duration between SIM_FADE_SCHEDULE segments [1.0]"),
    ("SIM_FADE_FILTER", "Fading", "value", "NAME",
     "Doppler-shaping filter convention: milstd (MIL-STD-188-110C) or codec2-2016 (legacy) [milstd]"),
    ("SIM_COMPLIANCE", "Fading", "flag", None,
     "App-E reference-channel mode: forces milstd filter, strips the rig BPF, refuses AGC/ALC [off]"),

    # --- Frequency and clock errors ---
    ("SIM_FOFF_HZ", "Frequency and clock errors", "value", "HZ",
     "static carrier offset, differential (+ on A->B, - on B->A) [0]"),
    ("SIM_FOFF_RAMP_HZ", "Frequency and clock errors", "value", "HZ",
     "carrier offset ramps linearly from SIM_FOFF_HZ to this value, then holds"),
    ("SIM_FOFF_RAMP_S", "Frequency and clock errors", "value", "S",
     "duration of the SIM_FOFF_RAMP_HZ ramp [600]"),
    ("SIM_FOFF_DEV_HZ", "Frequency and clock errors", "value", "HZ",
     "sinusoidal LO wobble deviation added to the carrier offset; requires SIM_FOFF_RATE_HZ [0]"),
    ("SIM_FOFF_RATE_HZ", "Frequency and clock errors", "value", "HZ",
     "sinusoidal LO wobble rate for SIM_FOFF_DEV_HZ [0]"),
    ("SIM_CLOCK_PPM", "Frequency and clock errors", "value", "PPM",
     "sample-clock error between stations, differential like SIM_FOFF_HZ [0]"),
    ("SIM_CLOCK_SLACK_MS", "Frequency and clock errors", "value", "MS",
     "SIM_CLOCK_PPM prefill; bounds the longest burst at slack/(ppm*1e-6) [20]"),

    # --- Transmitter and rig ---
    ("SIM_PA_P", "Transmitter and rig", "value", "N",
     "Rapp soft power-amp smoothness; 0 = hard clip at PEP (bit-exact baseline) [0]"),
    ("SIM_PA_VSAT", "Transmitter and rig", "value", "LSB",
     "power-amp saturation level for the SIM_PA_P soft-clip model [32767]"),
    ("SIM_RIG_BPF", "Transmitter and rig", "value", "NAME",
     "SSB rig passband preset: off, default(300-2700), data(150-2900), narrow(300-2400 Hz) [data]"),
    ("SIM_RIG_LO", "Transmitter and rig", "value", "HZ",
     "explicit rig bandpass low edge, overriding the SIM_RIG_BPF preset"),
    ("SIM_RIG_HI", "Transmitter and rig", "value", "HZ",
     "explicit rig bandpass high edge, overriding the SIM_RIG_BPF preset"),
    ("SIM_RIG_ORDER", "Transmitter and rig", "value", "N",
     "Butterworth filter order for the rig bandpass [6]"),
    ("SIM_ALC_PRESET", "Transmitter and rig", "value", "NAME",
     "ALC overshoot preset: modern (0.8 dB/25 ms) or legacy (7 dB/2 ms, ~5 s re-arm) [off]"),
    ("SIM_ALC_OVERSHOOT_DB", "Transmitter and rig", "value", "DB",
     "raw ALC overshoot, used when SIM_ALC_PRESET is off [0]"),
    ("SIM_ALC_SETTLE_MS", "Transmitter and rig", "value", "MS",
     "raw ALC settle time, used when SIM_ALC_PRESET is off [10]"),
    ("SIM_TR_KEY_MS", "Transmitter and rig", "value", "MS",
     "PTT-assert to RF-out settle time; the signal is clipped/absent for this long after keying [15]"),
    ("SIM_TR_UNKEY_MS", "Transmitter and rig", "value", "MS",
     "TX-end to RX-ready recovery time; the station stays deaf this long after unkeying [25]"),
    ("SIM_TR_JITTER_MS", "Transmitter and rig", "value", "MS",
     "per-key-edge uniform jitter +-J on the T/R settle times, instead of the fixed constants [0]"),
    ("SIM_LINK_DELAY_MS", "Transmitter and rig", "value", "MS",
     "fixed one-way propagation/turnaround delay applied to the faded TX signal [3]"),

    # --- Receiver ---
    ("SIM_RX_AGC", "Receiver", "value", "0|1|NAME",
     "RX AGC follower: 1 (2/100 ms legacy), data (10/25 ms), or voice (30/1000 ms) [off]"),
    ("SIM_RX_AGC_ATTACK_MS", "Receiver", "value", "MS",
     "raw AGC attack time, used when SIM_RX_AGC is 1 [2]"),
    ("SIM_RX_AGC_RELEASE_MS", "Receiver", "value", "MS",
     "raw AGC release time, used when SIM_RX_AGC is 1 [100]"),
    ("SIM_RX_AGC_TARGET", "Receiver", "value", "LSB",
     "AGC target output level [8000]"),
    ("SIM_RX_AGC_MAXGAIN_DB", "Receiver", "value", "DB",
     "AGC maximum applied gain [30]"),

    # --- Keying and half-duplex ---
    ("SIM_HALF_DUPLEX", "Keying and half-duplex", "flag", None,
     "gate each direction by VOX/PTT keying instead of full-duplex passthrough [off]"),
    ("SIM_PTT", "Keying and half-duplex", "flag", None,
     "key on real host PTT (via stdin relay) instead of audio-energy VOX; needs SIM_HALF_DUPLEX [off]"),
    ("SIM_KEY_THRESH", "Keying and half-duplex", "value", "LSB",
     "TX RMS level that VOX keying treats as keyed [800]"),
    ("SIM_HANG_MS", "Keying and half-duplex", "value", "MS",
     "VOX key hold-over through intra-burst gaps; must stay under the modem's TX->RX turnaround [80]"),
    ("SIM_KEYLOG", "Keying and half-duplex", "value", "PATH",
     "log VOX/PTT key transitions to <path>.a and <path>.b"),

    # --- Interference (QRM) ---
    ("SIM_QRM_OCC", "Interference (QRM)", "value", "FRAC",
     "in-channel CW/sweeper occupancy fraction, in [0, 1) [0]"),
    ("SIM_QRM_INR_DB", "Interference (QRM)", "value", "DB",
     "QRM carrier level over the in-channel noise power sigma^2 [10]"),
    ("SIM_QRM_INR_SPREAD_DB", "Interference (QRM)", "value", "DB",
     "spread of QRM carrier levels around SIM_QRM_INR_DB [6]"),
    ("SIM_QRM_INR_MAX_DB", "Interference (QRM)", "value", "DB",
     "cap on QRM carrier level above the noise floor [16]"),
    ("SIM_QRM_SWEEP", "Interference (QRM)", "flag", None,
     "add an OTHR-style sweeping carrier that chirps across a wide virtual band [off]"),
    ("SIM_QRM_SWEEP_INR_DB", "Interference (QRM)", "value", "DB",
     "sweeping carrier's level over the noise floor [10]"),
    ("SIM_QRM_SWEEP_RATE", "Interference (QRM)", "value", "HZ",
     "sweeping carrier's chirp rate [10]"),
    ("SIM_QRM_SWEEP_BAND_HZ", "Interference (QRM)", "value", "HZ",
     "virtual sweep span; in-channel duty = passband/span, must be >= 2400 [24000]"),
    ("SIM_QRM_REPLAY", "Interference (QRM)", "value", "SPEC",
     "comma-separated recorded-QRM WAV files/globs replacing generated noise; excl. SIM_QRM_OCC/SWEEP"),
    ("SIM_QRM_REPLAY_DIAL_HZ", "Interference (QRM)", "value", "HZ",
     "USB dial offset inside the SIM_QRM_REPLAY capture; 0 = capture centre [0]"),
    ("SIM_QRM_REPLAY_BW_HZ", "Interference (QRM)", "value", "HZ",
     "slice width taken from the SIM_QRM_REPLAY capture [3000]"),

    # --- FM channel ---
    ("SIM_FM_PORT", "FM channel", "value", "NAME",
     "FM port profile replacing the SSB rig chain: micspk or data9600 [off]"),
    ("SIM_FM_ORDER", "FM channel", "value", "N",
     "filter order for the FM port's audio shaping [6]"),
    ("SIM_FM_BAND", "FM channel", "value", "NAME",
     "band used to pick the SIM_FM_FADE regime's Doppler: 2m or 70cm [2m]"),
    ("SIM_FM_FADE", "FM channel", "value", "SPEC",
     "FM fade: off, fixed, pedestrian, mobile-urban/-highway, ionos:D:R, rayleigh:fD, rice:fD:K [off]"),
    ("SIM_FM_SHADOW", "FM channel", "value", "SPEC",
     "Suzuki log-normal shadowing sigma_db:tau_s, composes with SIM_FM_FADE [off]"),
    ("SIM_FM_NOISE_BW", "FM channel", "value", "HZ",
     "band-limit noise to the IONOS instrument's shaped-WGN bandwidth: off, 3000, or 6000 [off]"),
    ("SIM_FM_SQL", "FM channel", "value", "NAME",
     "micspk squelch mode: gated or off [gated]"),
    ("SIM_FM_SQL_OPEN_MS", "FM channel", "value", "MS",
     "squelch carrier-detect attack time [30]"),
    ("SIM_FM_SQL_THRESH", "FM channel", "value", "LSB",
     "squelch carrier-detect energy threshold, used on full-duplex runs [800]"),
    ("SIM_FM_SQL_TONE_MS", "FM channel", "value", "MS",
     "CTCSS decode settle time, applied only when SIM_FM_CTCSS_HZ is set [120]"),
    ("SIM_FM_SQL_TAIL_MS", "FM channel", "value", "MS",
     "squelch closing-tail burst duration [0]"),
    ("SIM_FM_SQL_TAIL_AMP", "FM channel", "value", "LSB",
     "squelch closing-tail burst amplitude [2000]"),
    ("SIM_FM_CTCSS_HZ", "FM channel", "value", "HZ",
     "CTCSS sub-audible tone frequency summed onto TX after the voice filter [0]"),
    ("SIM_FM_CTCSS_AMP", "FM channel", "value", "LSB",
     "CTCSS tone amplitude, ~10% full scale by default [3277]"),

    # --- Transport and clock ---
    ("SIM_LISTEN", "Transport and clock", "value", "[HOST:]PORT|HOST",
     "serve both stations over TCP instead of local devices; sets sock/virt-time/HD/PTT defaults"),
    ("SIM_TRANSPORT", "Transport and clock", "value", "NAME",
     "sample transport: alsa (four snd-aloop devices) or sock (framed unix sockets) [alsa]"),
    ("SIM_CLOCK", "Transport and clock", "value", "NAME",
     "clock mode: real_time (wall-paced) or virt_time (block-lockstep, sock only) [real_time]"),
    ("SIM_FS", "Transport and clock", "value", "HZ",
     "cable sample rate; 48000 is the validated default, 8000 matches a modem's sock rate [48000]"),
    ("SIM_NCH", "Transport and clock", "value", "N",
     "cable channel count; 1 for a mono-only station like FreeDATA on a raw aloop device [2]"),
    ("SIM_BLOCK", "Transport and clock", "value", "N",
     "pipe block size in frames per channel [1024]"),
    ("SIM_SOCK_DIR", "Transport and clock", "value", "PATH",
     "directory for the sock transport's a.sock/b.sock [/tmp/simsock-<pid>]"),
    ("SIM_SOCK_SHIM", "Transport and clock", "flag", None,
     "spawn sock_alsa_shim.py for both stations, bridging real aloop binaries onto sockets [off]"),
    ("SIM_SOCK_ACCEPT_S", "Transport and clock", "value", "S",
     "timeout waiting for both stations to connect over sock [30]"),
    ("SIM_SOCK_BUF", "Transport and clock", "value", "BYTES",
     "SO_SNDBUF/SO_RCVBUF size per sock-transport socket [65536]"),
    ("SIM_LISTEN_STALL_S", "Transport and clock", "value", "S",
     "end a SIM_LISTEN pair whose station answers nothing this long; 0 = wait forever [60]"),
    ("SIM_LISTEN_ONCE", "Transport and clock", "flag", None,
     "exit after the first SIM_LISTEN pair ends instead of waiting for the next pair [off]"),
    ("SIM_MAX_VIRTUAL_S", "Transport and clock", "value", "S",
     "bound a virt_time run in virtual seconds; 0 = unbounded (rely on the driver's wall timeout) [0]"),
    ("SIM_VIRT_MAX_RATIO", "Transport and clock", "value", "N",
     "cap the virtual clock at N x wall time, keeping wall scheduling delays small; 0 = unlimited [0]"),

    # --- Stats and debugging ---
    ("SEED", "Stats and debugging", "value", "N",
     "base RNG seed; per-direction seeds are SEED+11 (A->B) and SEED+22 (B->A) [1234]"),
    ("NP_STATS", "Stats and debugging", "value", "PATH",
     "write per-direction signal stats JSON to <path>.11 and <path>.22"),
    ("SIM_STATS_SKIP_BLOCKS", "Stats and debugging", "value", "N",
     "blocks skipped before tracking robust_peak, past the aloop cold-start transient [8]"),
    ("SIM_TXDUMP", "Stats and debugging", "value", "PATH",
     "dump each direction's post-gain, pre-noise TX stream to <path>.<src_name> as raw int16"),
    ("SIM_VERBOSE", "Stats and debugging", "flag", None,
     "print per-direction block-time health (p99/worst) on exit [off]"),
)
